# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

image: docker

variables:
  # Note: our staging branch is `main`
  STAGING_BRANCH: main

stages:
  - merge

merge-to-stage:
  stage: merge
  only:
    - java
    - web
    - bdd
  before_script: # Get the ssh key
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
    - mkdir -p ~/.ssh
    - ssh-keyscan forge.univ-lyon1.fr >> ~/.ssh/known_hosts
    - apk update && apk add git
  script: # Merge the dev branch into the staging branch
    # If this is the last job you can stay here, otherwise better clone the repo into a working directory
    # git clone <URL> <working-directory> && cd <working directory>
    - git fetch
    - git checkout "$STAGING_BRANCH"
    - git merge -s ours "origin/$CI_COMMIT_BRANCH" -m "Merge la branche de dev $CI_COMMIT_BRANCH en stage sur $STAGING_BRANCH"
    - git push -f https://${GIT_USERNAME}:${PERSONNAL_ACCESS_TOKEN}@${GIT_ORIGIN}/${GIT_PATH} "$STAGING_BRANCH"
